services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: semantic_butler
      POSTGRES_PASSWORD: "1lhXFE8rg1Ca-qmRdBw-Rtsv5vP2EiWc"
    volumes:
      - semantic_butler_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "RAfG7_Mba38iQdMlUmUf0TluEj844XF5"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: semantic_butler_test
      POSTGRES_PASSWORD: "lSU0pw3Gk_bRnVGN5ANySUAZcbFVmrWa"
    volumes:
      - semantic_butler_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "LNFRqsvGqMBBcwBQC0Tjmob2zr2_mXD-"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  semantic_butler_data:
  semantic_butler_test_data:
