name: semantic_butler_flutter
description: A new Flutter project with Serverpod.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '^3.5.0'
  flutter: '^3.24.0'

dependencies:
  bitsdojo_window: ^0.1.6
  cupertino_icons: ^1.0.5
  crypto: ^3.0.3
  file_picker: ^10.3.7
  http: ^1.2.0
  async: ^2.11.0
  extract_text: ^0.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.0.10
  path: ^1.9.0
  path_provider: ^2.1.5
  semantic_butler_client:
    path: ../semantic_butler_client
  serverpod_flutter: 3.1.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  fl_chart: ^0.69.0
  intl: ^0.20.2
  uuid: ^4.5.2
  flutter_markdown: ^0.7.4
  highlight: ^0.7.0
  markdown: ^7.2.2
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.5

dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  flutter_launcher_icons: ^0.14.1
  image: ^4.1.7
  msix: ^3.10.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/config.json
    - assets/
dependency_overrides:
  flutter_secure_storage: ^10.0.0

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# MSIX Configuration
msix_config:
  display_name: Filo
  publisher_display_name: Desk-Sense
  publisher: CN=Desk-Sense, O=Desk-Sense, L=San Francisco, S=California, C=US
  identity_name: com.desksense.filo
  msix_version: 1.0.4.0
  logo_path: assets/filo_logo.png
  capabilities: internetClient, location, microphone, privateNetworkClientServer
  install_certificate: true
